program: train_focal_loss.py
method: bayes
metric:
  goal: maximize
  name: "[Val] Mean IoU"
project: "deeplabv3-segmentation"

# Fixed parameters (not optimized)
parameters:
  # Dataset and model parameters
  dataset:
    value: "dna2025dataset"
  data_root:
    value: "./datasets/data"
  model:
    value: "deeplabv3_mobilenet"
  num_classes:
    value: 19
  pretrained_num_classes:
    value: 19
  output_stride:
    value: 16
  
  # Training parameters
  epochs:
    value: 120
  unfreeze_epoch:
    value: 15
  batch_size:
    value: 4
  val_batch_size:
    value: 4
  crop_size:
    value: 1024
  experiment_name:
    value: "focal_loss_sweep_optim"
  ckpt:
    value: "checkpoints/weighted_ce_sweep_optim/sweep_CE_best_model.pth"
  
  # WandB settings
  wandb_project:
    value: "deeplabv3-segmentation"
  wandb_notes:
    value: "Focal Loss fine-tuning: lr±20%, target_max_ratio±0.5, gamma optimization around optimal values"
  wandb_tags:
    value: "focal_loss,sweep,fine_tuning,parameter_interaction"
  
  # Early stopping parameters
  early_stop_patience:
    value: 10
  early_stop_min_delta:
    value: 0.001
  early_stop_metric:
    value: "Mean IoU"
  
  # Fixed training parameters
  weight_decay:
    value: 1e-4
  random_seed:
    value: 42
  print_interval:
    value: 10
  
  # Class weights parameters
  class_weights_file:
    value: "class_weights/dna2025dataset_sqrt_inv_freq_nc19.pth"
  
  # Dataset subset
  subset_ratio:
    value: 1.0
  

  # Parameters to optimize
  lr:
    values: [8e-6, 1e-5, 1.2e-5]
  
  focal_gamma:
    values: [1.0, 1.5, 2.0, 2.5, 3.0]
  
  target_max_ratio:
    values: [5.5, 6.0, 6.5]
